os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - CXX=g++-4.9
services:
  - redis-server
language: node_js
node_js:
  - 4.0
  - 4.4
  - 5.1
  - 5.5
  - 5.11
  - 6.0
  - 6.1
  - 6.11
  - 8.3
  - 9
  - 10
  - node
  - lts/argon
	- lts/boron
	- lts/carbon
  - lts/*
install: npm install
before_script:
  - "npm install -g grunt-cli"
  - "grunt build"
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls